<?php

namespace Tests;

use App\Structure\LinkedList\SingleLinkedList;
use PHPUnit\Framework\TestCase;

require_once __DIR__ . '/../vendor/autoload.php';

/**
 * 链表相关测试
 * @package Tests
 */
class LinkedListTest extends TestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testDivideInt()
    {
        $this->assertEquals(3, floor(7 / 2));
        $this->assertEquals(3, floor(6 / 2));
    }
}

